web:
  build: .
  command: bundle exec puma -p 3000
  links: &links
    - db
  environment: &envs
    - SKYLIGHT_AUTHENTICATION_STAGING=
    - PORT=3000
    - DATABASE_MASTER_URL=postgres://admin:password@db:5432
  ports:
    - "3000:3000"
  volumes:
    - .:/usr/app

dbvolume:
  image: busybox:latest
  volumes:
    - /usr/local/var/postgres:/var/lib/postgres

db:
  image: postgres:9.6.3-alpine
  ports:
    - "5432:5432"
  environment:
    - PGPASS=password
    - PGUSER=admin
    - PGDATA=/var/lib/pgsql/data
  volumes_from:
    - dbvolume
