require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe ShipmentsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Shipment. As you add validations to Shipment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { build(:shipment).attributes }

  let(:invalid_attributes) {
    {
      tracking_number: "not a usps tracking number",
      shipment_status: '93203'
    }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ShipmentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }
  let(:order) { build(:order) }
  let(:order_id) { order.id }

  describe "GET #index" do
    it "returns a success response" do
      shipment = Shipment.create! valid_attributes
      get :index, params: {}, session: valid_session
    end

    # USPS Tracking numbers are 20,22, or 30 digits. The norm is 22.
    # 30 digit tracking numbers are an application code + zip code + 22 digit tracking number
    it "shortens a 30 digit USPS tracking number to a 22 digit one" do
      shipment = create(:label_created)

      get :index, params: { tracking_number: "42010001#{shipment.tracking_number}"}, session: valid_session

      expect(response).to have_http_status(:ok)
      data = JSON.parse(response.body)['data']
      expect(data['tracking_number']).to eq(shipment.tracking_number)
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      shipment = Shipment.create! valid_attributes
      get :show, params: {id: shipment.to_param}, session: valid_session
      expect(response).to be_success
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Shipment" do
        expect {
          post :create, params: { order_id: order_id, shipment: valid_attributes }, session: valid_session
        }.to change(Shipment, :count).by(1)
      end

      it "renders a JSON response with the new shipment" do
        post :create, params: { order_id: order_id, shipment: valid_attributes }, session: valid_session
        expect(response).to have_http_status(:created)
        expect(response.content_type).to eq('application/json')
      end

      context 'without a tracking number' do        
        create_label_params = load_json_fixture('./spec/fixtures/shipstation/create_label_request_options.json')
        create_label_response = load_fixture('./spec/fixtures/shipstation/create_label_response.json')
        create_label_error_response = load_fixture('./spec/fixtures/shipstation/create_label_error_response.json')

        headers = { 
          "Authorization" => "Basic #{Base64.strict_encode64('test_api_key:test_api_secret')}"
        }

        url = 'https://ssapi.shipstation.com/shipments/createlabel'

        it 'creates a tracking number from the shipstation API' do
          create_label_params[:shipTo][:name] = order.name
          Timecop.freeze('2017-08-06')
          valid_attributes.delete('tracking_number')
          shipstation_response_object = object_double('response', code: 200, body: create_label_response )

          expect(HTTParty).to receive(:post).with(url, headers: headers, body: create_label_params).and_return(shipstation_response_object)
          post :create, params: { order_id: order_id, shipment: valid_attributes }, session: valid_session

          body = JSON.parse(response.body)['data']
          expect(Shipment.find(body['id']).tracking_number).to eq(JSON.parse(create_label_response)['trackingNumber'])
        end

        it 'creates tracking number for international orders' do
          create_label_int_params = load_json_fixture('./spec/fixtures/shipstation/create_label_request_int_options.json')
          create_label_int_response = load_fixture('./spec/fixtures/shipstation/create_label_response_int.json')
          create_label_int_params[:shipTo][:name] = order.name

          valid_attributes = build(:international_order).attributes
          valid_attributes.delete('tracking_number')
          Timecop.freeze('2017-08-06')

          shipstation_response_object = object_double('response', code: 200, body: create_label_response )

          expect(HTTParty).to receive(:post).with(url, headers: headers, body: create_label_int_params).and_return(shipstation_response_object)
          post :create, params: { order_id: order_id, shipment: valid_attributes }, session: valid_session

          body = JSON.parse(response.body)['data']
          expect(Shipment.find(body['id']).tracking_number).to eq(JSON.parse(create_label_response)['trackingNumber'])
          expect(body['tracking_number']).to eq JSON.parse(create_label_int_response)['trackingNumber']
        end

        it 'updates the shipment_status to label_created on successful storage of tracking_number' do
          create_label_params[:shipTo][:name] = order.name
          Timecop.freeze('2017-08-06')
          valid_attributes.delete('tracking_number')
          shipstation_response_object = object_double('response', code: 200, body: create_label_response )

          expect(HTTParty).to receive(:post).with(url, headers: headers, body: create_label_params).and_return(shipstation_response_object)
          post :create, params: { order_id: order_id, shipment: valid_attributes }, session: valid_session

          body = JSON.parse(response.body)['data']
          expect(Shipment.find(body['id']).shipment_status).to eq 'label_created'
        end

        it 'stores the label_data from the Shipstation api response' do
          valid_attributes.delete('tracking_number')
          shipstation_response_object = object_double('response', code: 200, body: create_label_response )

          expect(HTTParty).to receive(:post).and_return(shipstation_response_object)
           
          post :create, params: { order_id: order_id, shipment: valid_attributes }, session: valid_session 

          expect(Shipment.last.label_data).to eq(JSON.parse(create_label_response)['labelData'])

          body = JSON.parse(response.body)['label_data']
        end

        it 'handles errors from shipstation and raises an exception' do
          valid_attributes.delete('tracking_number')
          shipstation_response_object = object_double('response', code: 500, body: create_label_error_response)

          expect(HTTParty).to receive(:post).and_return(shipstation_response_object)
          expect{ 
            post :create, params: { order_id: order_id, shipment: valid_attributes }, session: valid_session
            }.to raise_error(ShipstationError)
        end
      end
    end

    context "with invalid params" do
      it "renders a JSON response with errors for the new shipment" do

        post :create, params: {shipment: invalid_attributes}, session: valid_session
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq('application/json')
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {
          shipment_status: 'shipped'
        }
      }

      it "updates the requested shipment" do
        shipment = Shipment.create! valid_attributes
        put :update, params: {id: shipment.to_param, shipment: new_attributes}, session: valid_session
        shipment.reload
        expect(shipment.shipment_status).to eq(new_attributes[:shipment_status])
      end

      it "renders a JSON response with the shipment" do
        shipment = Shipment.create! valid_attributes

        put :update, params: {id: shipment.to_param, shipment: valid_attributes}, session: valid_session
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to eq('application/json')
      end

      it 'updates the ship_date when the status changes to shipped' do
        expected_date = '2017-09-03'
        Timecop.freeze('2017-09-04')

        shipment = Shipment.create! valid_attributes

        put :update, params: {id: shipment.to_param, shipment: { shipment_status: 'shipped' }}, session: valid_session
        expect(response).to have_http_status(:ok)
        data = JSON.parse(response.body)['data']
        expect(data['ship_date']).to eq(expected_date)
        expect(Shipment.find(shipment.id).ship_date).to eq(expected_date)
      end
    end

    context "with invalid params" do
      it "renders a JSON response with errors for the shipment" do
        shipment = Shipment.create! valid_attributes

        put :update, params: {id: shipment.to_param, shipment: invalid_attributes}, session: valid_session
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq('application/json')
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested shipment" do
      shipment = Shipment.create! valid_attributes
      expect {
        delete :destroy, params: {id: shipment.to_param}, session: valid_session
      }.to change(Shipment, :count).by(-1)
    end
  end
end
